base: 'https://katalog.ddev.site'
baseVariants: {  }
errorHandling: {  }
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ''
    flag: global
    languageId: '0'
    solr_core_read: slub-typo3-de_DE
  -
    title: Englisch
    enabled: true
    base: /en/
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ''
    fallbackType: fallback
    fallbacks: '0'
    flag: gb
    languageId: '1'
    solr_core_read: slub-typo3-en_US
rootPageId: 2
routeEnhancers:
  CatalogId:
    type: Extbase
    limitToPages:
      - 2
    extension: Find
    plugin: Find
    routes:
      - routePath: '/id/{findId}/debug/{debug}'
        _controller: 'Search::detail'
        _arguments:
          findId: id
          findDebug: debug
      - routePath: '/id/{findId}'
        _controller: 'Search::detail'
        _arguments:
          findId: id
      - routePath: '/ppn/{findPpn}'
        _controller: 'Search::detail'
        _arguments:
          findPpn: 'ppn'
      - routePath: '/rsn/{findRsn}'
        _controller: 'Search::detail'
        _arguments:
          findRsn: 'rsn'
      - routePath: '/oclc/{findOclc}'
        _controller: 'Search::detail'
        _arguments:
          findOclc: 'oclc'
      - routePath: '/bc/{findBarcode}'
        _controller: 'Search::detail'
        _arguments:
          findBarcode: 'bc'
      - routePath: '/sicht/{findFlexibleviews}/id/{findId}'
        _controller: 'Search::detail'
        _arguments:
          findFlexibleviews: flexibleviews
          findId: id
      - routePath: '/sicht/{findFlexibleviews}'
        _controller: 'Search::index'
        _arguments:
          findFlexibleviews: flexibleviews
    defaults:
      findDebug: '1'
    aspects:
      findId:
        type: SlubCatalogId
      findDebug:
        type: StaticRangeMapper
        start: '0'
        end: '1'
      findPpn:
        type: SlubCatalogId
      findRsn:
        type: SlubCatalogId
      findOclc:
        type: SlubCatalogId
      findBarcode:
        type: SlubCatalogId
      findFlexibleviews:
        type: SlubCatalogId
    defaultController: 'Search::index'
routes: {  }
solr_enabled_read: false
solr_use_write_connection: false
